### ISSUE TITLE
Noob question!

### ISSUE THREAD

**Issue by f-bone** [cdhooper/mx29f1615_programmer#1]
apologies for the probably stupid question.

I have a few fake blue-pills I bought on AliExpress to use with the Greaseweazle project (https://github.com/keirf/greaseweazle) but they don't pass the blinky test. Can I use them with your project as my TL866II programmer can't seem to program 29f1615s? (it can read all 4 banks using the 16bit adapter and jumpers but programming *almost* always fails).

thank you!
br,
george

**Comment by cdhooper** [comment]
Hello George,
I've also got a TL866II programmer and also wasn't successful programming the MX29F1615 parts, even after modifying the Linux minipro utility.
Unfortunately you can't use the blue pill boards with this project. Although the Blue Pill does use an STM32F103 (or mostly compatible) CPU, it uses the 48-pin version of the part. This project requires the 100-pin version. You'd need one of these: STM32F105VCT6 (preferred), STM32F107VCT6, or STM32F103VCT6. Because of the chip shortage, these parts have all gotten much more expensive over the past year, to the point they are going for about 5x what they should be!

**Comment by f-bone** [comment]
Thank you for your time and detailed explanation!
